CreateConVar('ttt_pri_refill_time', 45, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_pri_refill_time_missed', 5, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_pri_damage_dete', 30, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_pri_damage_marker', 30, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_pri_show_messages', 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})